<?php

use App\Http\Controllers\Inmopro\AccessControl\PermissionController as AccessControlPermissionController;
use App\Http\Controllers\Inmopro\AccessControl\RoleController as AccessControlRoleController;
use App\Http\Controllers\Inmopro\AccessControl\RolePermissionController;
use App\Http\Controllers\Inmopro\AccessControl\UserRolesController;
use App\Http\Controllers\Inmopro\AccountsReceivableController;
use App\Http\Controllers\Inmopro\AdvisorAgendaEventController;
use App\Http\Controllers\Inmopro\AdvisorController;
use App\Http\Controllers\Inmopro\AdvisorLevelController;
use App\Http\Controllers\Inmopro\AdvisorMembershipController;
use App\Http\Controllers\Inmopro\AdvisorReminderController;
use App\Http\Controllers\Inmopro\AgendaController;
use App\Http\Controllers\Inmopro\AppBrandingController;
use App\Http\Controllers\Inmopro\AttentionTicketController;
use App\Http\Controllers\Inmopro\CashAccountController;
use App\Http\Controllers\Inmopro\CityController;
use App\Http\Controllers\Inmopro\ClientController;
use App\Http\Controllers\Inmopro\ClientTypeController;
use App\Http\Controllers\Inmopro\CommissionController;
use App\Http\Controllers\Inmopro\CommissionStatusController;
use App\Http\Controllers\Inmopro\DashboardController;
use App\Http\Controllers\Inmopro\DateroController;
use App\Http\Controllers\Inmopro\FinancialController;
use App\Http\Controllers\Inmopro\LotAiFollowUpSuggestionController;
use App\Http\Controllers\Inmopro\LotController;
use App\Http\Controllers\Inmopro\LotPreReservationController;
use App\Http\Controllers\Inmopro\LotStatusController;
use App\Http\Controllers\Inmopro\LotTransferConfirmationController;
use App\Http\Controllers\Inmopro\MembershipTypeController;
use App\Http\Controllers\Inmopro\ProcessDiagramsController;
use App\Http\Controllers\Inmopro\ProjectController;
use App\Http\Controllers\Inmopro\ProjectTypeController;
use App\Http\Controllers\Inmopro\ReportController;
use App\Http\Controllers\Inmopro\ReportSalesConfigController;
use App\Http\Controllers\Inmopro\TeamController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified'])->prefix('inmopro')->name('inmopro.')->group(function (): void {
    Route::middleware(['rbac.super-admin'])->prefix('access-control')->name('access-control.')->group(function (): void {
        Route::post('permissions/sync-routes', [AccessControlPermissionController::class, 'syncFromRoutes'])->name('permissions.sync-routes');
        Route::get('permissions', [AccessControlPermissionController::class, 'index'])->name('permissions.index');
        Route::get('roles/{role}/permissions', [RolePermissionController::class, 'edit'])->name('roles.permissions.edit');
        Route::put('roles/{role}/permissions', [RolePermissionController::class, 'update'])->name('roles.permissions.update');
        Route::get('users', [UserRolesController::class, 'index'])->name('users.index');
        Route::get('users/create', [UserRolesController::class, 'create'])->name('users.create');
        Route::post('users', [UserRolesController::class, 'store'])->name('users.store');
        Route::get('users/{user}/roles', [UserRolesController::class, 'edit'])->name('users.roles.edit');
        Route::put('users/{user}/roles', [UserRolesController::class, 'update'])->name('users.roles.update');
        Route::resource('roles', AccessControlRoleController::class)->except(['show']);
    });

    Route::middleware(['inmopro.permission'])->group(function (): void {
        Route::get('dashboard', DashboardController::class)->name('dashboard');
        Route::get('projects/excel-template', [ProjectController::class, 'excelTemplate'])->name('projects.excel-template');
        Route::post('projects/import-preview', [ProjectController::class, 'importPreview'])->name('projects.import-preview');
        Route::post('projects/import-confirm', [ProjectController::class, 'importConfirm'])->name('projects.import-confirm');
        Route::get('projects/{project}/assets/{asset}/download', [ProjectController::class, 'downloadAsset'])->name('projects.assets.download');
        Route::delete('projects/{project}/assets/{asset}', [ProjectController::class, 'destroyAsset'])->name('projects.assets.destroy');
        Route::patch('projects/{project}/toggle-active', [ProjectController::class, 'toggleActive'])->name('projects.toggle-active');
        Route::put('projects/{project}/lots/bulk-update', [ProjectController::class, 'bulkUpdateLots'])->name('projects.lots.bulk-update');
        Route::resource('projects', ProjectController::class);
        Route::resource('project-types', ProjectTypeController::class)
            ->except(['create', 'edit', 'show'])
            ->parameters(['project-types' => 'project_type']);
        Route::get('lots/export-pdf', [LotController::class, 'exportPdf'])->name('lots.export-pdf');
        Route::post('lots/{lot}/ai-follow-up-suggestion', LotAiFollowUpSuggestionController::class)
            ->middleware('throttle:ai')
            ->name('lots.ai-follow-up-suggestion');
        Route::resource('lots', LotController::class);
        Route::get('clients/search', [ClientController::class, 'search'])->name('clients.search');
        Route::get('clients/excel-template', [ClientController::class, 'excelTemplate'])->name('clients.excel-template');
        Route::get('clients/export-excel', [ClientController::class, 'exportExcel'])->name('clients.export-excel');
        Route::post('clients/import-preview', [ClientController::class, 'importPreview'])->name('clients.import-preview');
        Route::post('clients/import-confirm', [ClientController::class, 'importConfirm'])->name('clients.import-confirm');
        Route::resource('clients', ClientController::class);
        Route::resource('client-types', ClientTypeController::class)->parameters(['client-types' => 'client_type']);
        Route::resource('cities', CityController::class);
        Route::get('advisor-levels/excel-template', [AdvisorLevelController::class, 'excelTemplate'])->name('advisor-levels.excel-template');
        Route::get('advisor-levels/export-excel', [AdvisorLevelController::class, 'exportExcel'])->name('advisor-levels.export-excel');
        Route::post('advisor-levels/import-from-excel', [AdvisorLevelController::class, 'importFromExcel'])->name('advisor-levels.import-from-excel');
        Route::resource('advisor-levels', AdvisorLevelController::class)->parameters(['advisor-levels' => 'advisor_level']);
        Route::get('teams/excel-template', [TeamController::class, 'excelTemplate'])->name('teams.excel-template');
        Route::get('teams/export-excel', [TeamController::class, 'exportExcel'])->name('teams.export-excel');
        Route::post('teams/import-from-excel', [TeamController::class, 'importFromExcel'])->name('teams.import-from-excel');
        Route::get('advisors/search', [AdvisorController::class, 'search'])->name('advisors.search');
        Route::get('advisors/new', [AdvisorController::class, 'new'])->name('advisors.new');
        Route::get('advisors/{advisor}/profile-documents/{document}', [AdvisorController::class, 'downloadProfileDocument'])->name('advisors.profile-documents.download');
        Route::get('advisors/excel-template', [AdvisorController::class, 'excelTemplate'])->name('advisors.excel-template');
        Route::get('advisors/export-excel', [AdvisorController::class, 'exportExcel'])->name('advisors.export-excel');
        Route::post('advisors/import-preview', [AdvisorController::class, 'importPreview'])->name('advisors.import-preview');
        Route::post('advisors/import-confirm', [AdvisorController::class, 'importConfirm'])->name('advisors.import-confirm');
        Route::patch('advisors/{advisor}/toggle-active', [AdvisorController::class, 'toggleActive'])->name('advisors.toggle-active');
        Route::put('advisors/{advisor}/cazador-access', [AdvisorController::class, 'updateCazadorAccess'])->name('advisors.cazador-access.update');
        Route::put('advisors/{advisor}/material-items', [AdvisorController::class, 'updateMaterialItems'])->name('advisors.material-items.update');
        Route::post('advisors/{advisor}/material-items', [AdvisorController::class, 'storeMaterialItem'])->name('advisors.material-items.store');
        Route::resource('advisors', AdvisorController::class)->except(['destroy']);
        Route::resource('dateros', DateroController::class);
        Route::resource('teams', TeamController::class);
        Route::get('membership-types/{membership_type}/bulk-assign', [MembershipTypeController::class, 'bulkAssign'])->name('membership-types.bulk-assign');
        Route::post('membership-types/{membership_type}/bulk-assign', [MembershipTypeController::class, 'bulkAssignStore'])->name('membership-types.bulk-assign.store');
        Route::resource('membership-types', MembershipTypeController::class)->parameters(['membership-types' => 'membership_type']);
        Route::post('advisor-memberships/{advisor_membership}/installments', [AdvisorMembershipController::class, 'storeInstallment'])->name('advisor-memberships.installments.store');
        Route::post('advisor-memberships/{advisor_membership}/payments', [AdvisorMembershipController::class, 'storePayment'])->name('advisor-memberships.payments.store');
        Route::resource('advisor-memberships', AdvisorMembershipController::class)->parameters(['advisor-memberships' => 'advisor_membership']);
        Route::resource('lot-statuses', LotStatusController::class)->parameters(['lot-statuses' => 'lot_status']);
        Route::resource('commission-statuses', CommissionStatusController::class)->parameters(['commission-statuses' => 'commission_status']);
        Route::get('financial', [FinancialController::class, 'index'])->name('financial.index');
        Route::get('accounts-receivable', [AccountsReceivableController::class, 'index'])->name('accounts-receivable.index');
        Route::post('lots/{lot}/installments', [AccountsReceivableController::class, 'storeInstallment'])->name('lots.installments.store');
        Route::post('lots/{lot}/payments', [AccountsReceivableController::class, 'storePayment'])->name('lots.payments.store');
        Route::get('cash-accounts', [CashAccountController::class, 'index'])->name('cash-accounts.index');
        Route::post('cash-accounts', [CashAccountController::class, 'store'])->name('cash-accounts.store');
        Route::post('cash-accounts/{cash_account}/entries', [CashAccountController::class, 'storeEntry'])->name('cash-accounts.entries.store');
        Route::get('commissions', [CommissionController::class, 'index'])->name('commissions.index');
        Route::post('commissions/{commission}/mark-as-paid', [CommissionController::class, 'markAsPaid'])->name('commissions.mark-as-paid');
        Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
        Route::get('reports/pdf', [ReportController::class, 'pdf'])->name('reports.pdf');
        Route::get('reports/csv', [ReportController::class, 'csv'])->name('reports.csv');
        Route::get('report-settings', [ReportSalesConfigController::class, 'edit'])->name('report-settings.edit');
        Route::put('report-settings', [ReportSalesConfigController::class, 'update'])->name('report-settings.update');
        Route::get('branding', [AppBrandingController::class, 'edit'])->name('branding.edit');
        Route::put('branding', [AppBrandingController::class, 'update'])->name('branding.update');
        Route::get('attention-tickets/calendar', [AttentionTicketController::class, 'calendar'])->name('attention-tickets.calendar');
        Route::get('attention-tickets/{attention_ticket}/delivery-deed', [AttentionTicketController::class, 'deliveryDeed'])->name('attention-tickets.delivery-deed');
        Route::post('attention-tickets/{attention_ticket}/delivery-deed/mark-signed', [AttentionTicketController::class, 'markDeedSigned'])->name('attention-tickets.delivery-deed.mark-signed');
        Route::resource('attention-tickets', AttentionTicketController::class)->parameters(['attention-tickets' => 'attention_ticket']);
        Route::get('lot-pre-reservations', [LotPreReservationController::class, 'index'])->name('lot-pre-reservations.index');
        Route::post('lot-pre-reservations', [LotPreReservationController::class, 'store'])->name('lot-pre-reservations.store');
        Route::post('lot-pre-reservations/{lot_pre_reservation}/approve', [LotPreReservationController::class, 'approve'])->name('lot-pre-reservations.approve');
        Route::post('lot-pre-reservations/{lot_pre_reservation}/reject', [LotPreReservationController::class, 'reject'])->name('lot-pre-reservations.reject');
        Route::get('lot-transfer-confirmations', [LotTransferConfirmationController::class, 'index'])->name('lot-transfer-confirmations.index');
        Route::get('lots/{lot}/transfer-confirmation', [LotTransferConfirmationController::class, 'create'])->name('lots.transfer-confirmation');
        Route::post('lots/{lot}/transfer-confirmation', [LotTransferConfirmationController::class, 'store'])->name('lots.transfer-confirmation.store');
        Route::post('lot-transfer-confirmations/{lot_transfer_confirmation}/approve', [LotTransferConfirmationController::class, 'approve'])->name('lot-transfer-confirmations.approve');
        Route::post('lot-transfer-confirmations/{lot_transfer_confirmation}/reject', [LotTransferConfirmationController::class, 'reject'])->name('lot-transfer-confirmations.reject');
        Route::get('process-diagrams', ProcessDiagramsController::class)->name('process-diagrams.index');
        Route::get('agenda', [AgendaController::class, 'index'])->name('agenda.index');
        Route::post('advisor-agenda-events', [AdvisorAgendaEventController::class, 'store'])->name('advisor-agenda-events.store');
        Route::put('advisor-agenda-events/{advisor_agenda_event}', [AdvisorAgendaEventController::class, 'update'])->name('advisor-agenda-events.update');
        Route::delete('advisor-agenda-events/{advisor_agenda_event}', [AdvisorAgendaEventController::class, 'destroy'])->name('advisor-agenda-events.destroy');
        Route::post('advisor-reminders', [AdvisorReminderController::class, 'store'])->name('advisor-reminders.store');
        Route::put('advisor-reminders/{advisor_reminder}', [AdvisorReminderController::class, 'update'])->name('advisor-reminders.update');
        Route::delete('advisor-reminders/{advisor_reminder}', [AdvisorReminderController::class, 'destroy'])->name('advisor-reminders.destroy');
        Route::post('advisor-reminders/{advisor_reminder}/complete', [AdvisorReminderController::class, 'complete'])->name('advisor-reminders.complete');
    });
});
